name: staging
on:
  pull_request:
    branches: [main]
jobs:
  build:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build -- -c=staging
      - name: Copy index to list
        run: cp dist/index.html dist/list.html
      - name: Copy index to flow
        run: cp dist/index.html dist/flow.html
      - name: Copy index to 404
        run: cp dist/index.html dist/404.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.4.8
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: factoriolab/staging
          BRANCH: main
          FOLDER: dist
          CLEAN: true
